name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download

    - name: Unit Test
      run: |
        go test ./... -coverprofile=coverage.out 

    - name: GolangCI Lint
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.18.0
        ./bin/golangci-lint run --out-format checkstyle > golangci-lint.report || true

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master
      env: # Or as an environment variable
        SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

